### ISSUE TITLE
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, data/tfrecords/apple.tfrecords; No such file or directory

### ISSUE THREAD

**Issue by notabee** [engindeniz/Cycle-Dehaze#2]
I am getting this error while training.

**Comment by engindeniz** [comment]
It seems you want to use different dataset, however, we did not provide tfrecords of other datasets. You can try to find from [here](https://github.com/vanhuyz/CycleGAN-TensorFlow).
