### ISSUE TITLE
the test have no results

### ISSUE THREAD

**Issue by ghost** [engindeniz/Cycle-Dehaze#3]
when I test the model for track 1: indoor
it always automatically quit after printing "please wait.."

![image](https://user-images.githubusercontent.com/41133072/56464415-71f09e80-641b-11e9-9511-61de5abe111d.png)

And the results folder only has a "temp" subfolder.

Could you please help me?
@engindeniz 
Thanks in advance.

**Comment by yyz277322264** [comment]
I got the same problem. Have you solved it?

**Comment by yyz277322264** [comment]
> when I test the model for track 1: indoor
> it always automatically quit after printing "please wait.."
> 
> ![image](https://user-images.githubusercontent.com/41133072/56464415-71f09e80-641b-11e9-9511-61de5abe111d.png)
> 
> And the results folder only has a "temp" subfolder.
> 
> Could you please help me?
> @engindeniz
> Thanks in advance.



> when I test the model for track 1: indoor
> it always automatically quit after printing "please wait.."
> 
> ![image](https://user-images.githubusercontent.com/41133072/56464415-71f09e80-641b-11e9-9511-61de5abe111d.png)
> 
> And the results folder only has a "temp" subfolder.
> 
> Could you please help me?
> @engindeniz
> Thanks in advance.

I got the same problem. Have you solved it?

**Comment by ghost** [comment]
> when I test the model for track 1: indoor
> it always automatically quit after printing "please wait.."
> 
> And the results folder only has a "temp" subfolder.
> Could you please help me?
> @engindeniz
> Thanks in advance.
> 
> 
> when I test the model for track 1: indoor
> it always automatically quit after printing "please wait.."
> 
> And the results folder only has a "temp" subfolder.
> Could you please help me?
> @engindeniz
> Thanks in advance.
> 
> I got the same problem. Have you solved it?

No,sorry.

**Comment by engindeniz** [comment]
Do you have MATLAB in your environment?

**Comment by ghost** [comment]
Yes,I have.

**Comment by engindeniz** [comment]
Can you look at the logs folders and check if there is an error?

**Comment by ghost** [comment]
Ok, thanks for your reply. I'll check it out later.

**Comment by Tangyuny** [comment]
Hello! And  I tried to use this model for my own images, but I got a bunch of incapable image files, such as 'Error interpreting JPED image file' or 'Fatal error reading PNG image file'. Have you encountered this problem?

**Comment by engindeniz** [comment]
No, these errors are related to your images.

**Comment by lsgoodstudy** [comment]
I have found the reason.first,You should resize your image into 256*256. Second and the most important,In the inference.py ,line 41,the code should be modified as "wb+".
