### ISSUE TITLE
where can I find the NTIRE 2018 datasets?

### ISSUE THREAD

**Issue by sibangde** [engindeniz/Cycle-Dehaze#4]
I can't find the I-HAZE and O-HAZE datasets in the NTIRE2018 official website, can you tell me where can I download the datasets? or give the link

**Comment by engindeniz** [comment]
You can find the datasets from [I-HAZE](http://www.vision.ee.ethz.ch/ntire18/i-haze/) and [O_HAZE](http://www.vision.ee.ethz.ch/ntire18/o-haze/).
