### ISSUE TITLE
Tf2 code

### ISSUE THREAD

**Issue by Sharan-Babu** [engindeniz/Cycle-Dehaze#6]
Hi. Could I please get Tf 2 version of the same code. Thanking you in advance.

**Comment by engindeniz** [comment]
Unfortunately, we do not have a TF2 version of this code.

**Comment by adamcatto** [comment]
Hi @Sharan-Babu , if you are having trouble running the demo, you can just replace line 11 in `inference.py`:
`import tensorflow as tf` ––> `import tensorflow.compat.v1 as tf`
and the code should run.

additionally, I initially had trouble with the `matlab` command in `demo.sh`, but I created an alias at the top of the file and it worked fine (MacOS Big Sur)

**Comment by liangyanlin** [comment]
@adamcatto May I ask how to run MATLAB in the demo？
